language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo add-apt-repository -y ppa:cjohnston/ci
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update -qq
  - sudo apt-get install -qq libexpat1-dev libicu-dev autoconf automake
  - autoreconf -i
  - ./configure CXXFLAGS="-O0 -Wall -Wextra -ansi -pedantic"
script: make distcheck -j2
