language: cpp
compiler:
  - clang
  - gcc
before_script:
  - echo "\n" | sudo add-apt-repository ppa:dns/gnu
  - echo "\n" | sudo add-apt-repository ppa:cjohnston/ci
  - sudo apt-get update -qq
  - sudo apt-get install -qq libexpat1-dev autoconf automake
  - autoreconf -i
  - ./configure CXXFLAGS="-O0 -Wall -Wextra -ansi -pedantic"
script: make distcheck
